### ISSUE TITLE
-v verbose, can the level be set?

### ISSUE THREAD

**Issue by msj121** [txoof/codesign#4]
I see in the python code:

```
    args = get_args()

    verbose = 50 - (args.verbose*10) 
    if verbose < 10:
        verbose = 10
    logging.root.setLevel(verbose)
```

This doesn't seem documented, might be a good idea how to set verbose level? is possible. Apparently -v and args.verbose is set to 2 on my computer. So 20, thus logging is set to 30, but I don't get debugs. I personally re-wrote the scrip to force for debug by setting it to 10 verbose. 

All this, so I can see the command that checks notarize history because it was taking too long and possibly failing, though I assume thats my problem.

Specifically I found in "check_notarization" method the following lines useful for debugging, maybe a good idea to include in the verbose level and not debug?
I think line 398:
```
        logging.debug('running command:')
        logging.debug(' '.join(final_list))
```

Just a thought. But great script! Thanks so much, hopfully I can get it working on my app.

**Comment by txoof** [comment]
@msj121 
The intention of the code was to add multiple `-v` to increase the verbosity level. It's not well documented at all; I'll look at fixing that.

```shell
$ pycodesign.py -v -v -v -v
```

That should set it to the highest verbosity level.

PRs are welcome regarding your suggestions!

It also looks like altool is deprecated; I'll need to look into updating this to use whatever Apple is recommending these days.

**Comment by msj121** [comment]
I'll try to see what I can do when I get back around to codesigning to see if I can make a pull request and test it out.
