### ISSUE TITLE
Missing nbconvert template

### ISSUE THREAD

**Issue by jramboz** [txoof/codesign#5]
The `jupyter-nbconvert` command in the notebook is looking for a template named "python_clean". I can't seem to find this anywhere. Can you please provide the template?

It's not strictly necessary, but it seems like it will make processing PRs much easier on your end 😃

**Comment by jramboz** [comment]
Never mind, I found it in your [other repo](https://github.com/txoof/jupyter_templates). Thanks!

**Comment by txoof** [comment]
Thanks for sorting this out.

I love and hate Jupyter for the ease of noodling around, and the extra complexity it adds to doing simple tasks like actually packaging up and sharing a bit of python.
