### ISSUE TITLE
Clarifying questions

### ISSUE THREAD

**Issue by AmberSahdev** [txoof/codesign#8]
Hi @txoof, thanks for the library - codesigning for Apple seems to be needlessly complex.

I did have some questions though since I am fairly new to notarization and codesigning and happened upon this library through some Github discussions. 
1. The description mentions that this only code signs for terminal applications, is this true? i.e. does the signing not work for GUI applications? 
2. In this [How To](https://github.com/txoof/codesign/blob/main/Signing_and_Notarizing_HOWTO.md#sign-the-executable) doc, you specify Apple's codesign CLI commands to run; if we're running these manually, what does [pycodesign.py](https://github.com/txoof/codesign/blob/main/pycodesign.py) actually do? Are there steps after that we need that I'm unaware of?

Thanks!

**Comment by txoof** [comment]
@AmberSahdev 

1. This was primarily for CLIs, it should work for a GUI if it follows the same structure.
2. `pycodesign.py` does all the steps that the How To outlines, but tries to streamline it so you don't have to keep all those commands and switches in your head. The goal was to make publishing updates to internal software a little less painful. Every time I needed to fix a bug or bump a version, it was a pain to 

If you find problems, PRs are welcome! I haven't needed this tool in a while so it may be a little out of date.

**Comment by AmberSahdev** [comment]
Thank you @txoof! 

I guess I saw the [Requirements](https://github.com/txoof/codesign?tab=readme-ov-file#requirements) section in the readme and interpreted it as the per-requisite instead of the "goal". I understand now.
